apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-app.fullname" . }}-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  FLASK_ENV: "production"
  # Add other non-secret configs here if needed
