apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-app.fullname" . }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secretEnv.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secretEnv.POSTGRES_PASSWORD | quote }}
